### How to run the project
# Once you have dockers setup and runing in terminal
# Run docker-compose up --build -d 

version: "3.7"
services:
    # Configures the mysql service
    db:
        image: mysql:8.0
        container_name: newspoint-db
        # let the container to restart automatically unless it has been manualy stoped
        restart: unless-stopped
        # Maps the hosts port 33060 to the exposed port 3306 in the mysql container 
        ports:
            - 33060:3306
        # set environment variables for the service
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ALLOW_EMPTY_PASSWORD: "true"
            MYSQL_ROOT_PASSWORD:
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        # Map mysql volumes for performing initial database setup and populating the database with data
        volumes:
            - ./docker-compose/mysql:/docker-entrypoint-initdb.d
        # Attach container to newspointnetwork
        networks:
            - newspointnetwork
    # Configures the app (project) container
    app:
        build:
            # arguments to for user
            args:
                user: sam
                uid: 1000
            context: ./
            # Get the Dockerfile to use for image creation from the current directory
            dockerfile: Dockerfile
        image: newspoint
        container_name: newspoint-app
        restart: unless-stopped
        working_dir: /app
        # Map the current directory to the /app directory in the container
        volumes:
            - ./:/app
        networks:
            - newspointnetwork
    # Configures the nginx web server container
    nginx:
        image: nginx:alpine
        container_name: newspoint-nginx
        restart: unless-stopped
        depends_on:
            - db
            - app
        ports:
            - 8000:80
        volumes:
            - ./:/app
            # Gets the nginx server configuration from the project into the container config 
            - ./docker-compose/nginx:/etc/nginx/conf.d/
        networks:
            - newspointnetwork
# Create the network to be used by the containers
networks:
    newspointnetwork:
        driver: bridge
